Cloud/enterprise build fix (#1208)
- separated image building part to an action.
- separated enterprise and cloud builds.
- monitor is not required in cloud
- cloud will build images using vault secrets, as nextjs apps requires few envs at build time.

diff --git a/.github/actions/build-push-action/action.yml b/.github/actions/build-push-action/action.yml
--- a/.github/actions/build-push-action/action.yml
+++ b/.github/actions/build-push-action/action.yml
@@ -95,16 +95,16 @@ runs:
       run: |
         FLAT_BRANCH_VERSION=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9.-]//g')
 
-        semver_regex="^v([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)?$"
-        if [[ ! ${{ env.REL_VERSION }} =~ $semver_regex ]]; then
-          echo "Invalid Release Version Format : ${{ env.REL_VERSION }}"
-          echo "Please provide a valid SemVer version"
-          echo "e.g. v1.2.3 or v1.2.3-alpha-1"
-          echo "Exiting the build process"
-          exit 1  # Exit with status 1 to fail the step
-        fi
-
         if [ "${{ env.BUILD_RELEASE }}" == "true" ]; then
+          semver_regex="^v([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)?$"
+          if [[ ! ${{ env.REL_VERSION }} =~ $semver_regex ]]; then
+            echo "Invalid Release Version Format : ${{ env.REL_VERSION }}"
+            echo "Please provide a valid SemVer version"
+            echo "e.g. v1.2.3 or v1.2.3-alpha-1"
+            echo "Exiting the build process"
+            exit 1  # Exit with status 1 to fail the step
+          fi
+
           TAG=${{ env.IMG_OWNER }}/${{ env.IMG_NAME }}:${{ env.REL_VERSION }}
 
           if [ "${{ env.HARBOR_PUSH }}" == "true" ]; then
diff --git a/.github/workflows/build-branch-ee.yml b/.github/workflows/build-branch-ee.yml
--- a/.github/workflows/build-branch-ee.yml
+++ b/.github/workflows/build-branch-ee.yml
@@ -3,6 +3,23 @@ name: Branch Build Enterprise
 on:
   workflow_dispatch:
     inputs:
+      build_type:
+        description: 'Type of build to run'
+        required: true
+        type: choice
+        default: 'Build'
+        options:
+          - 'Build'
+          - 'Release'
+      releaseVersion:
+        description: "Release Version"
+        type: string
+        default: v0.0.0
+      isPrerelease:
+        description: "Is Pre-release"
+        type: boolean
+        default: false
+        required: true
       arm64:
         description: "Build for ARM64 architecture"
         required: false
@@ -15,6 +32,9 @@ on:
 env:
   TARGET_BRANCH: ${{ github.ref_name }}
   ARM64_BUILD: ${{ github.event.inputs.arm64 }}
+  BUILD_TYPE: ${{ github.event.inputs.build_type }}
+  RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
+  IS_PRERELEASE: ${{ github.event.inputs.isPrerelease }}
 
 jobs:
   branch_build_setup:
@@ -44,13 +64,15 @@ jobs:
       dh_img_proxy: ${{ steps.set_env_variables.outputs.DH_IMG_PROXY }}
       dh_img_monitor: ${{ steps.set_env_variables.outputs.DH_IMG_MONITOR }}
       harbor_push: ${{ steps.set_env_variables.outputs.HARBOR_PUSH }}
-      release_version: ${{ steps.set_env_variables.outputs.FLAT_RELEASE_VERSION }}
+      build_release: ${{ steps.set_env_variables.outputs.BUILD_RELEASE }}
+      build_prerelease: ${{ steps.set_env_variables.outputs.BUILD_PRERELEASE }}
+      release_version: ${{ steps.set_env_variables.outputs.RELEASE_VERSION }}
 
     steps:
       - id: set_env_variables
         name: Set Environment Variables
         run: |
-          if [ "${{ env.ARM64_BUILD }}" == "true" ] || ([ "${{ github.event_name }}" == "release" ] && [ "${{ env.IS_PRERELEASE }}" != "true" ]); then
+          if [ "${{ env.ARM64_BUILD }}" == "true" ] || ([ "${{ env.BUILD_TYPE }}" == "Release" ] && [ "${{ env.IS_PRERELEASE }}" != "true" ]); then
             echo "BUILDX_DRIVER=cloud" >> $GITHUB_OUTPUT
             echo "BUILDX_VERSION=lab:latest" >> $GITHUB_OUTPUT
             echo "BUILDX_PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_OUTPUT
@@ -64,6 +86,44 @@ jobs:
           BR_NAME=$( echo "${{ env.TARGET_BRANCH }}" |sed 's/[^a-zA-Z0-9.-]//g')
           echo "TARGET_BRANCH=$BR_NAME" >> $GITHUB_OUTPUT
 
+          echo "DH_IMG_WEB=web-enterprise" >> $GITHUB_OUTPUT
+          echo "DH_IMG_SPACE=space-enterprise" >> $GITHUB_OUTPUT
+          echo "DH_IMG_ADMIN=admin-enterprise" >> $GITHUB_OUTPUT
+          echo "DH_IMG_LIVE=live-enterprise" >> $GITHUB_OUTPUT
+          echo "DH_IMG_BACKEND=backend-enterprise" >> $GITHUB_OUTPUT
+          echo "DH_IMG_PROXY=proxy-enterprise" >> $GITHUB_OUTPUT
+          echo "DH_IMG_MONITOR=monitor-enterprise" >> $GITHUB_OUTPUT
+
+          BUILD_RELEASE=false
+          BUILD_PRERELEASE=false
+          RELVERSION="latest"
+          HARBOR_PUSH=false
+
+          if [ "${{ env.BUILD_TYPE }}" == "Release" ]; then
+            FLAT_RELEASE_VERSION=$(echo "${{ env.RELEASE_VERSION }}" | sed 's/[^a-zA-Z0-9.-]//g')
+            echo "FLAT_RELEASE_VERSION=${FLAT_RELEASE_VERSION}" >> $GITHUB_OUTPUT
+            HARBOR_PUSH=true
+
+            semver_regex="^v([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)?$"
+            if [[ ! $FLAT_RELEASE_VERSION =~ $semver_regex ]]; then
+              echo "Invalid Release Version Format : $FLAT_RELEASE_VERSION"
+              echo "Please provide a valid SemVer version"
+              echo "e.g. v1.2.3 or v1.2.3-alpha-1"
+              echo "Exiting the build process"
+              exit 1  # Exit with status 1 to fail the step
+            fi
+            BUILD_RELEASE=true
+            RELVERSION=$FLAT_RELEASE_VERSION
+
+            if [ "${{ env.IS_PRERELEASE }}" == "true" ]; then
+              BUILD_PRERELEASE=true
+            fi
+          fi
+          echo "BUILD_RELEASE=${BUILD_RELEASE}" >> $GITHUB_OUTPUT
+          echo "BUILD_PRERELEASE=${BUILD_PRERELEASE}" >> $GITHUB_OUTPUT
+          echo "RELEASE_VERSION=${RELVERSION}" >> $GITHUB_OUTPUT
+          echo "HARBOR_PUSH=${HARBOR_PUSH}" >> $GITHUB_OUTPUT
+
           if [ "${{ env.TARGET_BRANCH }}" == "master" ]; then
             echo "artifact_upload_to_s3=true" >> $GITHUB_OUTPUT
             echo "artifact_s3_suffix=latest" >> $GITHUB_OUTPUT
@@ -74,15 +134,6 @@ jobs:
             echo "artifact_upload_to_s3=false" >> $GITHUB_OUTPUT
             echo "artifact_s3_suffix=$BR_NAME" >> $GITHUB_OUTPUT
           fi
-
-          echo "DH_IMG_WEB=web-enterprise" >> $GITHUB_OUTPUT
-          echo "DH_IMG_SPACE=space-enterprise" >> $GITHUB_OUTPUT
-          echo "DH_IMG_ADMIN=admin-enterprise" >> $GITHUB_OUTPUT
-          echo "DH_IMG_LIVE=live-enterprise" >> $GITHUB_OUTPUT
-          echo "DH_IMG_BACKEND=backend-enterprise" >> $GITHUB_OUTPUT
-          echo "DH_IMG_PROXY=proxy-enterprise" >> $GITHUB_OUTPUT
-          echo "DH_IMG_MONITOR=monitor-enterprise" >> $GITHUB_OUTPUT
-          echo "HARBOR_PUSH=true" >> $GITHUB_OUTPUT
 
       - id: checkout_files
         name: Checkout Files
@@ -168,6 +219,9 @@ jobs:
       - name: Web Build and Push
         uses: ./.github/actions/build-push-action
         with:
+          build-release: ${{ needs.branch_build_setup.outputs.build_release }}
+          build-prerelease: ${{ needs.branch_build_setup.outputs.build_prerelease }}
+          release-version: ${{ needs.branch_build_setup.outputs.release_version }}
           docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
           dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
           harbor-push: ${{ needs.branch_build_setup.outputs.harbor_push }}
@@ -196,6 +250,9 @@ jobs:
       - name: Space Build and Push
         uses: ./.github/actions/build-push-action
         with:
+          build-release: ${{ needs.branch_build_setup.outputs.build_release }}
+          build-prerelease: ${{ needs.branch_build_setup.outputs.build_prerelease }}
+          release-version: ${{ needs.branch_build_setup.outputs.release_version }}
           docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
           dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
           harbor-push: ${{ needs.branch_build_setup.outputs.harbor_push }}
@@ -224,6 +281,9 @@ jobs:
       - name: Live Build and Push
         uses: ./.github/actions/build-push-action
         with:
+          build-release: ${{ needs.branch_build_setup.outputs.build_release }}
+          build-prerelease: ${{ needs.branch_build_setup.outputs.build_prerelease }}
+          release-version: ${{ needs.branch_build_setup.outputs.release_version }}
           docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
           dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
           harbor-push: ${{ needs.branch_build_setup.outputs.harbor_push }}
@@ -252,6 +312,9 @@ jobs:
       - name: Backend Build and Push
         uses: ./.github/actions/build-push-action
         with:
+          build-release: ${{ needs.branch_build_setup.outputs.build_release }}
+          build-prerelease: ${{ needs.branch_build_setup.outputs.build_prerelease }}
+          release-version: ${{ needs.branch_build_setup.outputs.release_version }}
           docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
           dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
           harbor-push: ${{ needs.branch_build_setup.outputs.harbor_push }}
@@ -280,6 +343,9 @@ jobs:
       - name: Proxy Build and Push
         uses: ./.github/actions/build-push-action
         with:
+          build-release: ${{ needs.branch_build_setup.outputs.build_release }}
+          build-prerelease: ${{ needs.branch_build_setup.outputs.build_prerelease }}
+          release-version: ${{ needs.branch_build_setup.outputs.release_version }}
           docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
           dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
           harbor-push: ${{ needs.branch_build_setup.outputs.harbor_push }}
@@ -322,6 +388,9 @@ jobs:
       - name: Monitor Build and Push
         uses: ./.github/actions/build-push-action
         with:
+          build-release: ${{ needs.branch_build_setup.outputs.build_release }}
+          build-prerelease: ${{ needs.branch_build_setup.outputs.build_prerelease }}
+          release-version: ${{ needs.branch_build_setup.outputs.release_version }}
           docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
           dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
           harbor-push: ${{ needs.branch_build_setup.outputs.harbor_push }}
